# Generated by Django 5.2 on 2025-05-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DbWash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(default=1111111, max_length=15),
            preserve_default=False,
        ),
    ]
