# Generated by Django 5.2.1 on 2025-05-19 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DbWash', '0002_cliente_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cita',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
